# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MB4gQwz3QbYxtL8t746XBfO49cYs2wy_
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
path = "/content/drive/MyDrive/Infosys_Model.xlsx"
df = pd.read_excel(path, sheet_name="Dashboard")
# Look at the first 5 rows
df.head()

df = pd.read_excel(path, sheet_name="Dashboard", header=1)
df = df.dropna(axis=1, how='all')
df.head()

df.info()

projected_profit_2027 = df.at[2, 'Mar-27']
print(f"Projected Profit for 2027: ₹{projected_profit_2027:,.2f} Cr")

import yfinance as yf

#Connect to the API
infy = yf.Ticker("INFY.NS")

#Get the current market price
live_price = infy.history(period="1d")['Close'].iloc[-1]

#Calculate the Upside
target_price_excel = 1893.6
upside_percentage = ((target_price_excel - live_price) / live_price) * 100

print(f"Live Price: ₹{live_price:.2f}")
print(f"Projected Upside: {upside_percentage:.2f}%")

# We use .loc[row_condition, column_name]
net_profit_row = df[df.iloc[:, 0].str.contains("Net Profit", na=False)]
projected_profit_2027 = net_profit_row['Mar-27'].values[0]
print(f"Corrected Projected Profit for 2027: ₹{projected_profit_2027:,.2f} Cr")

import sqlite3
import pandas as pd

#Connect to the database file
conn = sqlite3.connect('nifty_portfolio.db')
c = conn.cursor()
#Table 1: Company Metadata
c.execute('''CREATE TABLE IF NOT EXISTS Company_Registry
             (Ticker TEXT PRIMARY KEY, Name TEXT, Sector TEXT)''')

#Table 2: Financial Metrics
c.execute('''CREATE TABLE IF NOT EXISTS Stock_Metrics
             (Ticker TEXT, Price REAL, Five_Year_Avg_PE REAL, Current_PE REAL,
             FOREIGN KEY (Ticker) REFERENCES Company_Registry(Ticker))''')
conn.commit()

#Sample data for 50+ Nifty tickers
registry_data = [('INFY', 'Infosys', 'Tech'), ('TCS', 'Tata Consultancy', 'Tech'), ('HDFC', 'HDFC Bank', 'Banking')]
metrics_data = [('INFY', 1450, 28.5, 22.1), ('TCS', 3200, 30.0, 29.5), ('HDFC', 1500, 22.0, 16.5)]

c.executemany('INSERT OR REPLACE INTO Company_Registry VALUES (?,?,?)', registry_data)
c.executemany('INSERT OR REPLACE INTO Stock_Metrics VALUES (?,?,?,?)', metrics_data)
conn.commit()

#Joining tables and filtering for value
query = """
SELECT r.Name, m.Ticker, m.Current_PE, m.Five_Year_Avg_PE
FROM Company_Registry r
JOIN Stock_Metrics m ON r.Ticker = m.Ticker
WHERE m.Current_PE <= (m.Five_Year_Avg_PE * 0.80);
"""
discounted_portfolio = pd.read_sql_query(query, conn)
print("--- VALUE INVESTING SCREEN RESULTS ---")
print(discounted_portfolio)

import numpy as np
import matplotlib.pyplot as plt
initial_investment = 100000
years = 10
annual_return = 0.12
volatility = 0.30  # 30% risk factor
simulations = 1000

results = []
for i in range(simulations):
    # Simulating random market movements
    daily_returns = np.random.normal(annual_return/252, volatility/np.sqrt(252), 252*years)
    final_value = initial_investment * np.exp(np.sum(daily_returns))
    results.append(final_value)

plt.figure(figsize=(10, 6))
plt.hist(results, bins=50, color='skyblue', edgecolor='black')
plt.axvline(np.percentile(results, 5), color='red', linestyle='--', label='5th Percentile (Risk)')
plt.axvline(np.percentile(results, 95), color='green', linestyle='--', label='95th Percentile (Target)')
plt.title('Monte Carlo Simulation: 10-Year Wealth Projection')
plt.xlabel('Final Portfolio Value (₹)')
plt.ylabel('Frequency')
plt.legend()
plt.show()

print(f"95% Confidence Interval: ₹{np.percentile(results, 5):,.2f} to ₹{np.percentile(results, 95):,.2f}")